### ISSUE TITLE
[Documentation Request] How to add Lofelt to project make if not buildable on Simulator

### ISSUE THREAD

**Issue by danielocampo2** [jgrandchavin/lofelt#10]
Hi,

We're using the library and we're experiencing the described issue in the Readme about project not being buildable on Simulator. Could anyone here guide us through how to properly do that?
It'd be very helpful if that would be part of the documentation as well.

Thanks for the library!

**Comment by jgrandchavin** [comment]
Hello ! 

The problem is that Lofelt provide 2 frameworks for iOS : 1 suitable for debug and simulator and 1 suitable for prod and deploy on store. 

For the moment I implement only one and I don't know if it's possible to use one when build as debug and an other when build as Release. 

I will check that and I keep you informed.

**Comment by danielocampo2** [comment]
Thanks for the quick response. We would really appreciate that.

Currently we have to disable the library for development and only enable it back for releases, which is not ideal. If you know of a better temporary solution it'd be great too.

Thanks!

**Comment by jgrandchavin** [comment]
It has been fixed and released in version 0.1.0 available in pub.dev 👍

**Comment by danielocampo2** [comment]
@jgrandchavin Thanks a lot for this update. 
I am facing the following issue and I was wondering if you have any idea on how to get around it:
We are using flavors, so currently when it looks for the `$CONFIGURATION` in `import_framework.sh` is trying to find the configuration under `Debug-dev` (since that's our flavored config). This fails with a Not found error since, naturally, you added Debug and Release versions.
Do you know if there's a way to change our settings so that all Debug-x will point to Debug and Release-x will point to Release?

Thanks in advance.
