### ISSUE TITLE
Crash on iPhone which won't support CoreHaptics

### ISSUE THREAD

**Issue by jgrandchavin** [jgrandchavin/lofelt#5]

**Comment by joao-lofelt** [comment]
Hi @jgrandchavin,

I'm part of the team developing the Lofelt Studio SDK. In the latest Studio Beta 2021.3.25, we have fixed this. Users can now build and run for iPhones that don't support CoreHaptics. However, these devices won't support haptics playback.
Have a look and let us know if you had any issues.

Thanks a lot for creating this Flutter plugin. 🙏 !

**Comment by jgrandchavin** [comment]
Hello @joao-lofelt,

Yes I saw that ! I will test it as soon as possible !

Thanks for your answer and to follow the Flutter plugin 🙏
